#Define deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderservice
  template:
    metadata:
      labels:
        app: orderservice
    spec:
      containers:
        - name: orderservice
          image: nkrishnakumar/istio-order-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9005
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              memory: 512Mi

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9005
            initialDelaySeconds: 120
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9005
            initialDelaySeconds: 120
            timeoutSeconds: 10
          env:
            - name: EUREKA_URL
              value: "http://serviceregistry:8761/eureka/"
            - name: MONGO_HOST
              value: "database"
            - name: MONGO_HOST
              value: "database"
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USERNAME
              value: "admin"
            - name: MONGO_PASSWORD
              value: "password"
            - name: MONGO_DATABASE
              value: "ow_customers_db"
            #Kafka producer host detail
            - name: KAFKA_HOST
              value: kafka-0.kafka-headless.kk.svc.cluster.local

---

kind: Service
apiVersion: v1
metadata:
  name: orderservice
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9005
      targetPort: 9005
      protocol: TCP
  selector:
    app: orderservice
