#Define deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productservice
  template:
    metadata:
      labels:
        app: productservice
    spec:
      containers:
        - name: productservice
          image: nkrishnakumar/istio-product-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              memory: 512Mi

          #          readinessProbe:
          #            httpGet:
          #              path: product-service/actuator/health
          #              port: 8080
          #            initialDelaySeconds: 60
          #          livenessProbe:
          #            httpGet:
          #              path: product-service/actuator/health
          #              port: 8080
          #            initialDelaySeconds: 60
          #            timeoutSeconds: 10
          env:
            - name: SERVER_PORT
              value: "80"
            - name: CONFIG_SERVER_URL
              value: "http://configservice:8888/"
            - name: EUREKA_URL
              value: "http://serviceregistry:8761/eureka/"
            - name: MYSQL_HOST
              value: "mysql"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: "password"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: MONGO_HOST
              value: "database"
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USERNAME
              value: "admin"
            - name: MONGO_PASSWORD
              value: "password"
            - name: MONGO_DATABASE
              value: "ow_customers_db"

---

kind: Service
apiVersion: v1
metadata:
  name: productservice
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: productservice
