#Define deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
        - name: userservice
          image: nkrishnakumar/istio-user-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9010
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              memory: 512Mi

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9010
            initialDelaySeconds: 120
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9010
            initialDelaySeconds: 120
            timeoutSeconds: 10
          env:
            - name: EUREKA_URL
              value: "http://serviceregistry:8761/eureka/"
            - name: MYSQL_HOST
              value: "mysql"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: "password"
            #Kafka consumer host detail
            - name: KAFKA_HOST
              value: kafka.kk.svc.cluster.local
            - name: MONGO_HOST
              value: "database"
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USERNAME
              value: "admin"
            - name: MONGO_PASSWORD
              value: "password"
            - name: MONGO_DATABASE
              value: "ow_customers_db"

---

kind: Service
apiVersion: v1
metadata:
  name: userservice
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9010
      targetPort: 9010
      protocol: TCP
  selector:
    app: userservice
